give @s pa:ant_house
give @s pa:ant_housep
give @s pa:big_hirch_sapling
give @s pa:blue_mushroom_block
give @s pa:blue_mushroom_log
give @s pa:buddydirtblock
give @s pa:blue_mushroom_sapling
give @s pa:coconuti
give @s pa:coconutblockblock
give @s pa:coconut_tree_sapling
give @s pa:crackopencoconut
give @s pa:dogwood_planks_slab
give @s pa:dogwood_planks_stair
give @s pa:dogwood_planks_stair_fence
give @s pa:dogwood_sapling
give @s pa:dogwood_planks_door
give @s pa:dogwoodleafs
give @s pa:ender_crystal
give @s pa:dogwoodplanks
give @s pa:ender_cookie
give @s pa:dogwoodlog
give @s pa:ender_ore
give @s pa:ender_block
give @s pa:ender_sprinkles
give @s pa:eye_blossom_bush
give @s pa:gold_jasmine
give @s pa:fixe_water_diving_suit
give @s pa:jasmine
give @s pa:icewoodlog
give @s pa:jasmine_wine
give @s pa:lavender1
give @s pa:lavender
give @s pa:lavender_wine
give @s pa:lavenderywuqyqu
give @s pa:lilac_flower
give @s pa:lilies
give @s pa:lumi_lily_wine
give @s pa:lumi_lily
give @s pa:onion
give @s pa:onion_crop
give @s pa:muddydeepsand
give @s pa:onion_wine
give @s pa:redrobinhouse
give @s pa:rose_wine
give @s pa:rosebush
give @s pa:roses_bush
give @s pa:tall_wheat
give @s pa:weeping_willow_leafs
give @s pa:tall_wheat1
give @s pa:super_netherblock
give @s pa:water_diving_suit
give @s pa:weeping_willow_log
give @s pa:weeping_willow_planks
give @s pa:weeping_willow_planks_slab
give @s pa:weeping_willow_planks_stair
give @s pa:weepingwillow_planks_stair_fence
give @s pa:weeping_willow_planks_door
give @s pa:weeping_willow_sapling
give @s pa:wild_onion
give @s pa:zombie_slime
