summon projectile:floral_spore ~~~
summon projectile:floral_spore ~~~
summon projectile:floral_spore ~~~
summon projectile:floral_spore ~~~
summon projectile:floral_spore ~~~
summon projectile:floral_spore ~~~
summon projectile:floral_spore ~~~
summon projectile:floral_spore ~~~
summon projectile:floral_spore ~~~
summon projectile:floral_spore ~~~
summon projectile:floral_spore ~~~
summon projectile:floral_spore ~~~