import "petalFlower"
import "radialLeafFunction"
import 'onInteract'
import 'onTick'
import 'doorFunction'
import 'customSapling'
import 'doublePlant'
import 'onPlayerDestroy'
import 'onPlayerPlaced'
import 'weaponEffects'
import 'toolDurability'
import 'armorEffects'
import 'blockDurability'
import 'mapleLog'
import 'leavesLoot'
import 'flowerSpread'
import 'whisperingWillow'
import 'fallingLeaves'
import './Advancements/handler';