give @s tt:black_blood_ore 64
give @s tt:black_nether_gold_ore 64
give @s tt:black_netherrack 64
give @s tt:black_quartz_ore 64
give @s tt:blood_block 64
give @s tt:blood_ore 64
give @s tt:bricks_basalt 64
give @s tt:bricks_black_netherrack 64
give @s tt:bricks_netherrack 64
give @s tt:circular_basalt 64
give @s tt:circular_black_netherrack 64
give @s tt:circular_netherrack 64
give @s tt:magma_basalt 64
give @s tt:magma_blackstone 64
give @s tt:magma_obsidian 64
give @s tt:mosaic_basalt 64
give @s tt:mosaic_black_netherrack 64
give @s tt:mosaic_netherrack 64
give @s tt:pillarside_basalt 64
give @s tt:pillarside_black_netherrack 64
give @s tt:pillarside_netherrack 64
give @s tt:tiles_medium_basalt 64
give @s tt:tiles_medium_black_netherrack 64
give @s tt:tiles_medium_netherrack 64
titleraw @a title {"rawtext":[{"text":"§byou have obtained all the blocks"}]}